lib: [
  "_build/install/default/lib/test-ec-make/META"
  "_build/install/default/lib/test-ec-make/Test_ec_make.a"
  "_build/install/default/lib/test-ec-make/Test_ec_make.cma"
  "_build/install/default/lib/test-ec-make/Test_ec_make.cmxa"
  "_build/install/default/lib/test-ec-make/Test_ec_make.cmxs"
  "_build/install/default/lib/test-ec-make/dune-package"
  "_build/install/default/lib/test-ec-make/opam"
  "_build/install/default/lib/test-ec-make/test_ec_make.cmi"
  "_build/install/default/lib/test-ec-make/test_ec_make.cmt"
  "_build/install/default/lib/test-ec-make/test_ec_make.cmx"
  "_build/install/default/lib/test-ec-make/test_ec_make.ml"
]
