image: ocaml/opam2:4.07

stages:
  - build

build-test-lint:
  # https://docs.gitlab.com/ee/ci/yaml/#cache
  stage: build
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - _opam
  before_script:
    # Always update system package manager + setup OPAM env
    - sudo apt-get update && sudo apt-get upgrade -y
    - eval $(opam env)
    - opam update
  script:
    # Install external dependencies
    - opam depext -i -y conf-rust zarith
    - opam install --deps-only --with-test -y .
    # Install the static library from rustc
    - git clone https://gitlab.com/dannywillems/rustc-bls12-381 /tmp/rustc-bls12-381
    - cd /tmp/rustc-bls12-381
    - cargo build --release
    - mkdir -p ${OPAM_SWITCH_PREFIX}/lib/librustc-bls12-381
    - cp target/release/librustc_bls12_381.a ${OPAM_SWITCH_PREFIX}/lib/librustc-bls12-381/librustc_bls12_381.a
    - opam install .
    # Run test
    - opam install alcotest
    - cd ${CI_PROJECT_DIR}
    - dune runtest
    # Lint
    - opam install ocamlformat
    - ocamlformat --check src/*.ml*
    - ocamlformat --check test/*.ml*
    - ocamlformat --check benchmark/*.ml*
