image: ocaml/opam2:ubuntu-lts

stages:
  - build
  - test

build:
  # https://docs.gitlab.com/ee/ci/yaml/#cache
  stage: build
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - _opam
  script:
    - sudo apt install m4 -y
    - opam switch create 4.07.0 
    - opam install --deps-only -t -y .

test:
  stage: test
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - _opam
  script:
    - eval $(opam env)
    - opam switch
    - dune runtest
