image: ocaml/opam2:4.07

stages:
  - build

build-and-test:
  # https://docs.gitlab.com/ee/ci/yaml/#cache
  stage: build
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - _opam
  script:
    - sudo apt install m4 cargo -y
    - eval $(opam env)
    - opam install --deps-only -t -y .
    # Install the static library from rustc
    - git clone https://gitlab.com/dannywillems/rustc-bls12-381 /tmp/rustc-bls12-381
    - cd /tmp/rustc-bls12-381
    - cargo build
    - mkdir -p ${OPAM_SWITCH_PREFIX}/lib/librustc-bls12-381
    - cp target/debug/librustc_bls12_381.a ${OPAM_SWITCH_PREFIX}/lib/librustc-bls12-381/librustc_bls12_381.a
    - opam install .
    - opam install alcotest
    - cd ${CI_PROJECT_DIR}
    - dune runtest

lint:
  dependencies:
    - build-and-test
  stage: build
  script:
    - eval $(opam env)
    - opam install ocamlformat
    - ocamlformat --check src/*.ml*
    - ocamlformat --check test/*.ml*
